/**
 * Fixture payloads for transactional email previews — no production customer data.
 */
const FIXTURES = {
  sme_welcome: {
    displayName: 'Thandi Nkosi',
    companyName: 'Nkosi Supplies (Pty) Ltd',
  },
  youth_agent_welcome: {
    displayName: 'Sipho Dlamini',
  },
  attendance_payment_confirmed: {
    requestId: 'TB-REQ-DEMO-001',
    smeName: 'Thandi Nkosi',
    smeCompany: 'Nkosi Supplies (Pty) Ltd',
    tenderTitle: 'Supply and Delivery of ICT Equipment',
    tenderNumber: 'RFQ 184/2026',
    department: 'City of Johannesburg',
    briefingDate: '2026-08-18',
    briefingDateLabel: '18 August 2026',
    briefingTime: '10:00 SAST',
    briefingVenue: 'Johannesburg Civic Centre',
    paymentAmount: 34900,
    quotedFee: 34900,
    briefingPriceCents: 34900,
    pricingVersion: '2026-08-v349',
    currency: 'ZAR',
    paymentReference: 'TB-PF-DEMO-001',
    paymentLabel: 'R349.00',
  },
  agent_assignment: {
    requestId: 'TB-REQ-DEMO-001',
    agentName: 'Sipho Dlamini',
    displayName: 'Sipho Dlamini',
    tenderTitle: 'Supply and Delivery of ICT Equipment',
    tenderNumber: 'RFQ 184/2026',
    department: 'City of Johannesburg',
    briefingDate: '2026-08-18',
    briefingDateLabel: '18 August 2026',
    briefingTime: '10:00 SAST',
    briefingVenue: 'Johannesburg Civic Centre',
    reportDueAt: '2026-08-19T10:00:00+02:00',
    reportDueAtLabel: '19 August 2026, 10:00',
    meetingType: 'Compulsory briefing',
  },
  sme_agent_allocated: {
    requestId: 'TB-REQ-DEMO-001',
    smeCompany: 'Nkosi Supplies (Pty) Ltd',
    tenderTitle: 'Supply and Delivery of ICT Equipment',
    tenderNumber: 'RFQ 184/2026',
    briefingDate: '2026-08-18',
    briefingDateLabel: '18 August 2026',
    briefingTime: '10:00 SAST',
    briefingVenue: 'Johannesburg Civic Centre',
  },
  attendance_proof_available: {
    requestId: 'TB-REQ-DEMO-001',
    tenderTitle: 'Supply and Delivery of ICT Equipment',
    tenderNumber: 'RFQ 184/2026',
    briefingDate: '2026-08-18',
    briefingDateLabel: '18 August 2026',
    attendanceStatus: 'Confirmed',
  },
  briefing_report_ready: {
    requestId: 'TB-REQ-DEMO-001',
    tenderTitle: 'Supply and Delivery of ICT Equipment',
    tenderNumber: 'RFQ 184/2026',
    briefingDate: '2026-08-18',
    briefingDateLabel: '18 August 2026',
    reportSubmittedAt: '2026-08-18T15:30:00+02:00',
    reportSubmittedAtLabel: '18 August 2026, 15:30',
  },
  agent_report_reminder_pending: {
    requestId: 'TB-REQ-DEMO-001',
    stage: 'pending',
    tenderTitle: 'Supply and Delivery of ICT Equipment',
    tenderNumber: 'RFQ 184/2026',
    reportDueAt: '2026-08-19T10:00:00+02:00',
    reportDueAtLabel: '19 August 2026, 10:00',
  },
  agent_report_reminder_due_soon: {
    requestId: 'TB-REQ-DEMO-001',
    stage: 'due_soon',
    tenderTitle: 'Supply and Delivery of ICT Equipment',
    tenderNumber: 'RFQ 184/2026',
    reportDueAt: '2026-08-19T10:00:00+02:00',
    reportDueAtLabel: '19 August 2026, 10:00',
  },
  agent_report_reminder_overdue: {
    requestId: 'TB-REQ-DEMO-001',
    stage: 'overdue',
    tenderTitle: 'Supply and Delivery of ICT Equipment',
    tenderNumber: 'RFQ 184/2026',
    reportDueAt: '2026-08-19T10:00:00+02:00',
    reportDueAtLabel: '19 August 2026, 10:00',
  },
  report_delay_update: {
    requestId: 'TB-REQ-DEMO-001',
    tenderTitle: 'Supply and Delivery of ICT Equipment',
    tenderNumber: 'RFQ 184/2026',
    attendanceStatus: 'Recorded / in progress',
  },
  admin_report_overdue: {
    requestId: 'TB-REQ-DEMO-001',
    agentName: 'Sipho Dlamini',
    agentId: 'agent-demo',
    tenderTitle: 'Supply and Delivery of ICT Equipment',
    tenderNumber: 'RFQ 184/2026',
    briefingDate: '2026-08-18',
    reportDueAt: '2026-08-19T10:00:00+02:00',
    reportDueAtLabel: '19 August 2026, 10:00',
    overdueLabel: '6h',
  },
}

const GALLERY = [
  { id: 'sme_welcome', templateId: 'sme_welcome', label: 'SME welcome', fixture: 'sme_welcome' },
  { id: 'youth_agent_welcome', templateId: 'youth_agent_welcome', label: 'Youth Agent welcome', fixture: 'youth_agent_welcome' },
  {
    id: 'attendance_payment_confirmed',
    templateId: 'attendance_payment_confirmed',
    label: 'Payment confirmation',
    fixture: 'attendance_payment_confirmed',
  },
  { id: 'agent_assignment', templateId: 'agent_assignment', label: 'Agent assignment', fixture: 'agent_assignment' },
  { id: 'sme_agent_allocated', templateId: 'sme_agent_allocated', label: 'SME allocation confirmation', fixture: 'sme_agent_allocated' },
  {
    id: 'attendance_proof_available',
    templateId: 'attendance_proof_available',
    label: 'Proof of attendance',
    fixture: 'attendance_proof_available',
  },
  { id: 'briefing_report_ready', templateId: 'briefing_report_ready', label: 'Report ready', fixture: 'briefing_report_ready' },
  {
    id: 'agent_report_reminder_pending',
    templateId: 'agent_report_reminder',
    label: 'Report reminder — pending',
    fixture: 'agent_report_reminder_pending',
  },
  {
    id: 'agent_report_reminder_due_soon',
    templateId: 'agent_report_reminder',
    label: 'Report reminder — due soon',
    fixture: 'agent_report_reminder_due_soon',
  },
  {
    id: 'agent_report_reminder_overdue',
    templateId: 'agent_report_reminder',
    label: 'Report reminder — overdue',
    fixture: 'agent_report_reminder_overdue',
  },
  { id: 'report_delay_update', templateId: 'report_delay_update', label: 'SME delay update', fixture: 'report_delay_update' },
  { id: 'admin_report_overdue', templateId: 'admin_report_overdue', label: 'Admin overdue escalation', fixture: 'admin_report_overdue' },
]

function getFixture(id) {
  return FIXTURES[id] || {}
}

module.exports = { FIXTURES, GALLERY, getFixture }
