/**
 * National procurement source registry — Phase 18.
 * Extend here; do not hard-code URLs in scrapers.
 */

const PROCUREMENT_SOURCES = [
  {
    id: 'etenders',
    name: 'National Treasury eTenders',
    type: 'national',
    baseUrl: 'https://www.etenders.gov.za',
    scrapeMethod: 'ocds_api',
    supportsPdfExtraction: true,
    supportsBriefingDetection: true,
    category: 'national',
    province: 'National',
    enabled: true,
  },
  {
    id: 'cidb_itender',
    name: 'CIDB iTender',
    type: 'national',
    baseUrl: 'https://www.cidb.org.za',
    scrapeMethod: 'html_list',
    supportsPdfExtraction: true,
    supportsBriefingDetection: true,
    category: 'construction',
    province: 'National',
    enabled: true,
  },
  {
    id: 'eskom',
    name: 'Eskom',
    type: 'soe',
    baseUrl: 'https://www.eskom.co.za',
    scrapeMethod: 'html_list',
    supportsPdfExtraction: true,
    supportsBriefingDetection: true,
    category: 'energy',
    province: 'National',
    enabled: true,
  },
  {
    id: 'transnet',
    name: 'Transnet',
    type: 'soe',
    baseUrl: 'https://www.transnet.net',
    scrapeMethod: 'html_list',
    supportsPdfExtraction: true,
    supportsBriefingDetection: true,
    category: 'transport',
    province: 'National',
    enabled: true,
  },
  {
    id: 'prasa',
    name: 'PRASA',
    type: 'soe',
    baseUrl: 'https://www.prasa.com',
    scrapeMethod: 'html_list',
    supportsPdfExtraction: true,
    supportsBriefingDetection: true,
    category: 'transport',
    province: 'National',
    enabled: true,
  },
  {
    id: 'sanral',
    name: 'SANRAL',
    type: 'soe',
    baseUrl: 'https://www.nra.co.za',
    scrapeMethod: 'html_list',
    supportsPdfExtraction: true,
    supportsBriefingDetection: true,
    category: 'infrastructure',
    province: 'National',
    enabled: true,
  },
  {
    id: 'city_of_johannesburg',
    name: 'City of Johannesburg',
    type: 'municipal',
    baseUrl: 'https://www.joburg.org.za',
    scrapeMethod: 'html_list',
    supportsPdfExtraction: true,
    supportsBriefingDetection: true,
    category: 'municipal',
    province: 'Gauteng',
    enabled: true,
  },
  {
    id: 'tshwane',
    name: 'City of Tshwane',
    type: 'municipal',
    baseUrl: 'https://www.tshwane.gov.za',
    scrapeMethod: 'html_list',
    supportsPdfExtraction: true,
    supportsBriefingDetection: true,
    category: 'municipal',
    province: 'Gauteng',
    enabled: true,
  },
  {
    id: 'ekurhuleni',
    name: 'City of Ekurhuleni',
    type: 'municipal',
    baseUrl: 'https://www.ekurhuleni.gov.za',
    scrapeMethod: 'html_list',
    supportsPdfExtraction: true,
    supportsBriefingDetection: true,
    category: 'municipal',
    province: 'Gauteng',
    enabled: true,
  },
  {
    id: 'ethekwini',
    name: 'eThekwini Municipality',
    type: 'municipal',
    baseUrl: 'https://www.durban.gov.za',
    scrapeMethod: 'html_list',
    supportsPdfExtraction: true,
    supportsBriefingDetection: true,
    category: 'municipal',
    province: 'KwaZulu-Natal',
    enabled: true,
  },
  {
    id: 'cape_town',
    name: 'City of Cape Town',
    type: 'municipal',
    baseUrl: 'https://www.capetown.gov.za',
    scrapeMethod: 'html_list',
    supportsPdfExtraction: true,
    supportsBriefingDetection: true,
    category: 'municipal',
    province: 'Western Cape',
    enabled: true,
  },
  {
    id: 'gauteng_treasury',
    name: 'Gauteng Provincial Treasury',
    type: 'provincial',
    baseUrl: 'https://www.gauteng.gov.za',
    scrapeMethod: 'html_list',
    supportsPdfExtraction: true,
    supportsBriefingDetection: true,
    category: 'provincial',
    province: 'Gauteng',
    enabled: true,
  },
  {
    id: 'western_cape_scm',
    name: 'Western Cape SCM',
    type: 'provincial',
    baseUrl: 'https://www.westerncape.gov.za',
    scrapeMethod: 'html_list',
    supportsPdfExtraction: true,
    supportsBriefingDetection: true,
    category: 'provincial',
    province: 'Western Cape',
    enabled: true,
  },
  {
    id: 'kzn_treasury',
    name: 'KZN Provincial Treasury',
    type: 'provincial',
    baseUrl: 'https://www.kzn.gov.za',
    scrapeMethod: 'html_list',
    supportsPdfExtraction: true,
    supportsBriefingDetection: true,
    category: 'provincial',
    province: 'KwaZulu-Natal',
    enabled: true,
  },
]

function getSourceById(id) {
  return PROCUREMENT_SOURCES.find((s) => s.id === id) || null
}

function getEnabledSources() {
  return PROCUREMENT_SOURCES.filter((s) => s.enabled)
}

module.exports = {
  PROCUREMENT_SOURCES,
  getSourceById,
  getEnabledSources,
}
